Repository rakutentech/android-miniapp, pull requests merged in 2022-11, with the labels that each got.

#494 [MINI-5532] Enable permission settings on mini app top bar
  testapp/src/main/AndroidManifest.xml
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppFactory.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppPermissionAdapter.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppViewModel.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/DemoAppMainActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppDisplayFragment.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppDownloadedListActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppDownloadedListAdapter.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppPermissionSettingsActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/MiniAppPermissionSettingsAdapter.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/permission/PermissionsUtils.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
  testapp/src/main/res/layout/settings_fragment.xml
  testapp/src/main/res/menu/miniapp_display_menu.xml
Labels: enhancement, demo-app

#503 [MINI-5641] Negative value displayed for available size if storage limit is set in decimal value
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSize.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MessageBridgeSecurestorageDispatcherSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MiniAppSecureStorageDispatcherSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
  testapp/build.gradle
Labels: bug, SDK, v5.1.0

#506 [MINI-5641] Negative value displayed for available size if storage limit is set in decimal value
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSize.kt
Labels: bug, SDK, v5.1.0

#508 [MINI-5539] Shows configuration saved dialog
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/DemoAppMainActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppListFragment.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/viewModel/MiniAppListViewModel.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/viewModel/SettingsViewModel.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/viewModel/SettingsViewModelFactory.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/AppSettings.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/cache/Cache.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/cache/MiniAppConfigCache.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/cache/MiniAppConfigData.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/settings/cache/MiniAppListCache.kt
  testapp/src/main/res/values/strings.xml
Labels: enhancement, don't review, major change, demo-app

#511 [MINI-5711] MiniApps that do not use secure storage should not have a DB created by default.
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
Labels: enhancement, SDK, v5.1.0

#514 [MIN-5711] Clear storage should only delete all the records only and not the whole table itself.
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
Labels: enhancement, SDK, v5.1.0

#510 [MINI-5696] Missing events for open and close dialog
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/deeplink/SchemeActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppShareWindow.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/preload/PreloadMiniAppWindow.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppDisplayFragment.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/MiniAppListFragment.kt
Labels: enhancement, demo-app

#515 Hotfix changes for Android SDK v5.0.1
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppMessageBridge.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/js/MiniAppSecureStorageDispatcher.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSize.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MessageBridgeSecurestorageDispatcherSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/js/securestoragedispatcher/MiniAppSecureStorageDispatcherSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
  testapp/build.gradle
Labels: hotfix

#517 [MINI-5733] Error while entering data once the MiniApp is closed and reopened.
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
Labels: bug, SDK, v5.0.1

#512 [MINI-5729] Update Repository Readme
  README.md
Labels: documentation

#518 [MINI-5737] Error on clear storage data once the MiniApp is closed and reopened.
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseImpl.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
Labels: bug, SDK, v5.0.1

#520 Candidate
  CHANGELOG.md
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorage.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseImpl.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/MiniAppSecureStorageSpec.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabaseSpec.kt
Labels: SDK

#521 [NO TICKET] Add cross icon to clear input fields in Demo app
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/miniapptabs/fragments/SettingsFragment.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/AccessTokenActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ContactListActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/userdata/ProfileSettingsActivity.kt
  testapp/src/main/res/layout/access_token_settings_activity.xml
  testapp/src/main/res/layout/mini_app_input_activity.xml
  testapp/src/main/res/layout/points_activity.xml
  testapp/src/main/res/layout/profile_settings_activity.xml
  testapp/src/main/res/layout/qa_settings_activity.xml
  testapp/src/main/res/layout/settings_fragment.xml
  testapp/src/main/res/values/dimens.xml
Labels: demo-app

#513 [MINI-5634] Back to display by url when exit external webview
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/helper/AppHelper.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/display/MiniAppDisplayActivity.kt
  testapp/src/main/java/com/rakuten/tech/mobile/testapp/ui/input/MiniAppByUrlActivity.kt
Labels: bug, demo-app

#523 [MINI-5767] Fixing the NoSuchAlgorithmFound crash for Android 7 and below.
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/database/MiniAppSecureDatabase.kt
  miniapp/src/main/java/com/rakuten/tech/mobile/miniapp/storage/util/MiniAppDatabaseEncryptionUtil.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/TestData.kt
  miniapp/src/test/java/com/rakuten/tech/mobile/miniapp/storage/util/MiniAppDatabaseEncryptionUtilSpec.kt
Labels: bug, SDK, v5.1.0
